PowerBi/Models/Reportes/Logo.cs
using Core.Models.Common;
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace TarjetasColpatria.Models.Reportes
{
    public class Logo : EntityWithIntId
    {
        public bool Estado { get; set; } = true;
        public string Ruta { get; set; }
        public Guid? ReporteId { get; set; }

        [ForeignKey("ReporteId")]
        public Reportes Reporte { get; set; }
    }
}

PowerBi/Models/Reportes/Reportes.cs
using Core.Models.Common;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TarjetasColpatria.Models.Reportes
{
    public class Reportes : Entity
    {
        [DisplayName("Nombre")]
        public string Nombre { get; set; }

        [DisplayName("Dashboard")]
        public Guid? DashboardId { get; set; }

        [DisplayName("Estado")]
        public Boolean Estado { get; set; }

        [DisplayName("Url")]
        public string url { get; set; }

        public Guid area { get; set; }

        public Guid campana { get; set; }

        public string WORKGROUP_NAME { get; set; }

        public string WORKGROUP_ID { get; set; }

        public string REPORT_NAME { get; set; }

        public string REPORT_ID { get; set; }

        public string REPORT_FILTER { get; set; }

        public Guid TIPO_REPORTE { get; set; }

        public string REPORT_DETALLE { get; set; }

                          
        //llaves foranea


        [ForeignKey("DashboardId")]
        public Dashboard.Dashboard Dashboard { get; set; }

        [ForeignKey("area")]
        public Areas.Areas AreaId { get; set; }

        [ForeignKey("campana")]
        public campanas campanaId { get; set; }

        [ForeignKey("TIPO_REPORTE")]
        public TipoReporte tiporeporteId { get; set; }
    }

 }

PowerBi/Models/Reportes/TipoReporte.cs
using Core.Models.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TarjetasColpatria.Models.Reportes
{
    public class TipoReporte:Entity
    {

        public string Nombre { get; set; }

        public Boolean Estado { get; set; }

    }
}

PowerBi/Models/Reportes/UserReports.cs
using Core.Models.Common;
using Core.Models.User;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TarjetasColpatria.Models.Reportes
{
    public class UserReports:Entity
    {
        [DisplayName("Usuario")]
        public Guid IdUsuario { get; set; }

        [DisplayName("Reporte")]
        public Guid IdReporte { get; set; }



        //foraneas

        [ForeignKey("IdUsuario")]
        public User user { get; set; }

        [ForeignKey("IdReporte")]
        public Reportes reportes { get; set; }


    }
}

PowerBi/Controllers/ReportesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Core.Models;
using Core.Models.Security;
using PagedList;
using TarjetasColpatria.Models.Areas;
using TarjetasColpatria.Models.Dashboard;
using TarjetasColpatria.Models.Permisos;
using TarjetasColpatria.Models.Reportes;



namespace TarjetasColpatria.Controllers
{
    public class ReportesController : Controller
    {
        private Contexto db = new Contexto();

        // GET: Reportes

        public ActionResult IndexPrincipal(string cuenta, string nombre, int? i)
        {
            TempData["message"] = TempData["message"];

          

            if (!string.IsNullOrEmpty(cuenta) || !string.IsNullOrEmpty(nombre))
            {
                var reportes = db.Reportes.Include(r => r.AreaId)
                                     .Include(r => r.campanaId)
                                     .Include(r => r.Dashboard)
                                     .Include(r => r.tiporeporteId)
                                     .Where(x => x.campanaId.Nombre.Trim().Contains(cuenta.Trim()) || x.Nombre.Trim().Contains(nombre.Trim())).ToList().ToPagedList(i ?? 1, 5);

                return View(reportes);

            }
            else
            {
                var reportes = db.Reportes.Include(r => r.AreaId)
                                      .Include(r => r.campanaId)
                                      .Include(r => r.Dashboard)
                                      .Include(r => r.tiporeporteId)
                                      .ToList().ToPagedList(i ?? 1, 5);

                return View(reportes);

            }


        }

        public ActionResult Index(Guid? Id)
        {
            Dashboard dashboards = db.Dashboard.Find(Id);

            if (dashboards == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ViewBag.Nombre = dashboards.Nombre;
            ViewBag.Id = Id;
            ViewBag.reportes = db.Reportes.Include(s => s.Dashboard).Where(u => u.DashboardId == Id);

            var reportes = db.Reportes;
            return View(reportes.ToList());
        }

        // GET: Reportes/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var reportes = db.Reportes.Find(id);

          

            if (reportes == null)
            {
                return HttpNotFound();
            }
            return View(reportes);
        }
        [CustomAuthorize(Roles = "Administrador")]
        // GET: Reportes/Create
        public ActionResult Create()
        {



            ViewBag.DashboardId = new SelectList(db.Dashboard, "Id", "Nombre");
            ViewBag.area = new SelectList(db.areas, "Id", "Nombre");
            ViewBag.campana = new SelectList(db.campanas.Where(m => m.Areas == db.areas.FirstOrDefault().Id), "Id", "Nombre");   

           ViewBag.DashboardId = new SelectList(db.Dashboard, "Id", "Nombre");
            ViewBag.TIPO_REPORTE = new SelectList(db.tiporeporte, "Id", "Nombre");
            return View();
        }

        public JsonResult Getcampana(Guid Id)
        {

            var camp = db.campanas.Where(m => m.Areas == Id);
            return Json(camp);

        }



        // POST: Reportes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nombre,DashboardId,Estado,url,area,campana,WORKGROUP_NAME,WORKGROUP_ID,REPORT_NAME,REPORT_ID,REPORT_FILTER,TIPO_REPORTE,REPORT_DETALLE,CreatedAt,UpdatedAt,DeletedAt,CreatedBy,UpdatedBy")] Reportes reportes, string Nombre)
        {
            if (ModelState.IsValid)
            {

                var arrayCadena = reportes.url.Split('/');
                bool badera = false;

                ViewBag.errorValidacion = "";

                if (reportes.TIPO_REPORTE.ToString().Equals("9009b408-96e8-421a-85ac-03b6d75f9cdf"))//Reporte
                {
                    //Cuando es reporte tiene el siguiente Patron
                    //https://app.powerbi.com/groups/3771fe1b-427c-4163-95af-ab0612ec570c/reports/9b039007-32e0-4eca-b03d-1bb1c9d4d781/ReportSection

                    if (arrayCadena[3].Equals("groups") && arrayCadena[5].Equals("reports"))
                    {
                        badera = true;
                        reportes.WORKGROUP_ID = arrayCadena[4];
                        reportes.REPORT_ID = arrayCadena[6];
                    }
                    else
                    {
                        ViewBag.errorValidacion = "El tipo de reporte no concuerda con la Url idicada.";
                    }

                }
                else
                if (reportes.TIPO_REPORTE.ToString().Equals("e8b65c29-d5eb-4d65-9215-8904b1b9cb90"))//Dashboard
                {



                }


                if (badera == true)
                {
                    reportes.Id = Guid.NewGuid();
                    db.Reportes.Add(reportes);
                    db.SaveChanges();
                    return RedirectToAction("IndexPrincipal");
                }

            }

            var Id = reportes.DashboardId;
            ViewBag.Nombre = Nombre;
            ViewBag.Id = Id;
            ViewBag.reportes = db.Reportes.Include(s => s.Dashboard).Where(u => u.DashboardId == Id);
            ViewBag.area = new SelectList(db.areas, "Id", "Nombre", reportes.area);
            ViewBag.campana = new SelectList(db.campanas, "Id", "Nombre", reportes.campana);
            ViewBag.DashboardId = new SelectList(db.Dashboard, "Id", "Nombre", reportes.DashboardId);
            ViewBag.TIPO_REPORTE = new SelectList(db.tiporeporte, "Id", "Nombre", reportes.TIPO_REPORTE);


            return View();

        }




        // GET: Reportes/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Reportes reportes = db.Reportes.Find(id);

            if (reportes == null)
            {
                return HttpNotFound();
            }

            ViewBag.DashboardId = new SelectList(db.Dashboard, "Id", "Nombre", reportes.DashboardId);

            ViewBag.campana = new SelectList(db.campanas, "Id", "Nombre", reportes.campana);

            ViewBag.area = new SelectList(db.areas, "Id", "Nombre", reportes.area);

            ViewBag.TIPO_REPORTE = new SelectList(db.tiporeporte, "Id", "Nombre", reportes.TIPO_REPORTE);

            return View(reportes);
        }

        // POST: Reportes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Reportes reportes)
        {
            if (ModelState.IsValid)
            {

            
                var arrayCadena = reportes.url.Split('/');
                bool badera = false;

                ViewBag.errorValidacion = "";

                if (reportes.TIPO_REPORTE.ToString().Equals("9009b408-96e8-421a-85ac-03b6d75f9cdf"))//Reporte
                {
                //Cuando es reporte tiene el siguiente Patron
                //https://app.powerbi.com/groups/3771fe1b-427c-4163-95af-ab0612ec570c/reports/9b039007-32e0-4eca-b03d-1bb1c9d4d781/ReportSection

                 if(arrayCadena[3].Equals("groups") && arrayCadena[5].Equals("reports"))
                    { 
                     badera = true;
                     reportes.WORKGROUP_ID = arrayCadena[4];
                     reportes.REPORT_ID = arrayCadena[6];
                    }
                    else
                    {
                        ViewBag.errorValidacion = "El tipo de reporte no concuerda con la Url idicada.";
                    }

                }
                else
                if (reportes.TIPO_REPORTE.ToString().Equals("e8b65c29-d5eb-4d65-9215-8904b1b9cb90"))//Dashboard
                {

                    //Cuando es reporte tiene el siguiente Patron
                    //https://app.powerbi.com/groups/d327716e-30bf-456f-8d54-fd006a990d34/dashboards/b4e3cb55-097a-417d-925d-0181c530b64d

                    if (arrayCadena[3].Equals("groups") && arrayCadena[5].Equals("dashboards"))
                    {
                        badera = true;
                        reportes.WORKGROUP_ID = arrayCadena[4];
                        reportes.REPORT_ID = arrayCadena[6];
                    }
                    else
                    {
                        ViewBag.errorValidacion = "El tipo de dashboards no concuerda con la Url idicada.";
                    }

                }

                if(badera == true)
                { 
                    db.Entry(reportes).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index/"+reportes.DashboardId);
                }

            }

            ViewBag.DashboardId = new SelectList(db.Dashboard, "Id", "Nombre", reportes.DashboardId);

            //ViewBag.DashboardId = new SelectList(db.Dashboard, "Id", "Nombre", reportes.DashboardId);

            ViewBag.campana = new SelectList(db.campanas, "Id", "Nombre", reportes.campana);

            ViewBag.area = new SelectList(db.areas, "Id", "Nombre", reportes.area);

            ViewBag.TIPO_REPORTE = new SelectList(db.tiporeporte, "Id", "Nombre", reportes.TIPO_REPORTE);

PowerBi/Views/Reportes/Create.cshtml
@model TarjetasColpatria.Models.Reportes.Reportes

@{
    ViewBag.Title = "Create";
}

@{
    ViewBag._Active = "Create";
    ViewBag._Panel = "Home";
}



<div class="box box-danger">
    <div class="box-header with-border">
        <h3 class="box-title">Crear Reporte</h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        <div class="row">
            <div class="col-md-12">

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })

                                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.DashboardId, "DashboardId", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("DashboardId", null, "Sin Seleccionar", htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.DashboardId, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        
                        <div class="form-group">
                            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <select id="Estado" name="Estado" class="form-control">
                                    <option value="false">Seleccione</option>
                                    <option value="true">Activo</option>
                                    <option value="false">Inactivo</option>
                                </select>
                            </div>
                        </div>
                                              

                        <div class="form-group">
                            @Html.LabelFor(model => model.url, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.url, new { htmlAttributes = new { @class = "form-control" } })

                                @Html.ValidationMessageFor(model => model.url, "", new { @class = "text-danger" })
                            </div>
                        </div>


                        <div class="form-group">
                            @Html.LabelFor(model => model.area, "Area", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("area", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.area, "", new { @class = "text-danger" })
                            </div>
                        </div>



                        <div class="form-group">
                            @Html.LabelFor(model => model.campana, "Cuenta", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("campana", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.campana, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.WORKGROUP_NAME, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.WORKGROUP_NAME, new { htmlAttributes = new { @class = "form-control" } })

                                @Html.ValidationMessageFor(model => model.WORKGROUP_NAME, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.WORKGROUP_ID, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.WORKGROUP_ID, new { htmlAttributes = new { @class = "form-control" } })

                                @Html.ValidationMessageFor(model => model.WORKGROUP_ID, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.REPORT_ID, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.REPORT_ID, new { htmlAttributes = new { @class = "form-control" } })

                                @Html.ValidationMessageFor(model => model.REPORT_ID, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.REPORT_FILTER, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.REPORT_FILTER, new { htmlAttributes = new { @class = "form-control" } })

                                @Html.ValidationMessageFor(model => model.REPORT_FILTER, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.TIPO_REPORTE, "TIPO_REPORTE", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("TIPO_REPORTE", null, "Sin Seleccionar", htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.TIPO_REPORTE, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.REPORT_DETALLE, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.REPORT_DETALLE, new { htmlAttributes = new { @class = "form-control" } })

                                @Html.ValidationMessageFor(model => model.REPORT_DETALLE, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                @ViewBag.errorValidacion
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Crear" class="btn btn-success" />
                                @Html.ActionLink("Regresar", "IndexPrincipal", null, new { @class = "btn btn-default" })

                            </div>
                        </div>
                    </div>
                }

                
               
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            $("#area").change(function () {
                $("#campana").empty();
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("Getcampana")',
                    dataType: 'json',
                    data: {Id: $("#area").val() },
                    success: function (camp) {
                        $.each(camp, function (i, camp) {
                            $("#campana").append('<option value="'
                                + camp.Id + '">'
                                + camp.Nombre + '</option>');


                        });
                    },
                    error: function (ex) {
                        alert('error al visualizar las campanas' + ex);
                    }
                });
                return false;
            })
        });
    </script>
}

PowerBi/Views/Reportes/Delete.cshtml
@model TarjetasColpatria.Models.Reportes.Reportes

@{
    ViewBag.Title = "Delete";
}

@{
    ViewBag._Active = "Delete";
    ViewBag._Panel = "Home";
}


<div class="box box-danger">
    <div class="box-header with-border">
        <h3 class="box-title">¿Esta seguro que desea eliminar este elemento?</h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        <div class="row">
            <div class="col-md-12 col-xs-12 col-sm-12">
                <table id="tabla" class="table table-bordered table-hover">
                    <tbody>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Dashboard.Nombre)
                            </th>

                            <td>
                                @Html.DisplayFor(model => model.Dashboard.Nombre)
                            </td>
                        </tr>

                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Nombre)
                            </th>

                            <td>
                                @Html.DisplayFor(model => model.Nombre)
                            </td>
                        </tr>

                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Estado)
                            </th>

                            <td>
                                @Html.DisplayFor(model => model.Estado)
                            </td>
                        </tr>

                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.url)
                            </th>

                            <td>
                                @Html.DisplayFor(model => model.url)
                            </td>
                        </tr>

                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.CreatedAt)
                            </th>

                            <td>
                                @Html.DisplayFor(model => model.CreatedAt)
                            </td>
                        </tr>

                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.UpdatedAt)
                            </th>

                            <td>
                                @Html.DisplayFor(model => model.UpdatedAt)
                            </td>
                        </tr>

                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.DeletedAt)
                            </th>

                            <td>
                                @Html.DisplayFor(model => model.DeletedAt)
                            </td>
                        </tr>

                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.CreatedBy)
                            </th>

                            <td>
                                @Html.DisplayFor(model => model.CreatedBy)
                            </td>
                        </tr>

                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.UpdatedBy)
                            </th>

                            <td>
                                @Html.DisplayFor(model => model.UpdatedBy)
                            </td>
                        </tr>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Eliminar" class="btn btn-danger" />
        @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-default" })
    </div>
}
</div>

PowerBi/Views/Reportes/IndexPrincipal.cshtml
@model IPagedList<TarjetasColpatria.Models.Reportes.Reportes>

@using PagedList.Mvc;
@using PagedList;


@{
    ViewBag.Title = "Index";
}

@{
    ViewBag._Active = "Index";
    ViewBag._Panel = "Home";
}

@if (TempData["message"] != null)
{
    <div class="alert alert-danger  alert-dismissible" role="alert">
        @TempData["message"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

<div class="box box-danger">
    <div class="box-header with-border">    
       
    </div><!-- /.box-header -->
    <div class="box-body">
        <div class="row">
            @using (Html.BeginForm("IndexPrincipal", "Reportes"))
            {
                <div class="col-xs-12 col-md-12 col-lg-12">
                    <div class=" col-md-3 form-group">
                        <label>Cuenta</label>
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-road"></i>
                            </div>
                            <input type="text" class="form-control" id="cuenta" name="cuenta" placeholder="Ingrese el nombre de la cuenta">
                        </div>
                    </div>

                    <div class=" col-md-3 form-group">
                        <label>Nombre Reporte</label>
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-road"></i>
                            </div>
                            <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Ingrese el nombre del reporte">
                        </div>
                    </div>
                    <div class="col-md-6 inline-form form-group">
                        <label for=""> Acciones </label>
                        <div class="input-group">
                            <input type="submit" class="btn btn-primary" id="btnCon" value="consultar">
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
</div>



<div class="box box-danger">
    <div class="box-header with-border">
        <h3 class="box-title">Lista de Reportes</h3>
    </div><!-- /.box-header -->
    <div class="box-body">

        <div class="row">
            <div class="col-md-12">
                <table id="tabla" class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>
                                Area
                            </th>
                            <th>
                                Cuenta
                            </th>
                            <th>
                                Nombre Dashboard
                            </th>
                            <th>
                                Tipo Reporte
                            </th>
                            <th>
                                Nombre Reporte
                            </th>
                            <th>
                                Estado
                            </th>

                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.AreaId.Nombre)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.campanaId.Nombre)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Dashboard.Nombre)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.tiporeporteId.Nombre)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Nombre)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Estado)
                                </td>
                                <td>
                                    @Html.ActionLink("Editar", "Edit", new { id = item.Id }, new { @class = "btn btn-xs btn-success" })
                                    @Html.ActionLink("Detalle", "Details", new { id = item.Id }, new { @class = "btn btn-xs btn-default" })
                                    @Html.ActionLink("Eliminar", "Delete", "Reportes", new { id = item.Id }, new { @class = "btn btn-xs btn-danger", onclick = "return confirm('Está seguro de eliminar el registro?');" })

                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

                @Html.PagedListPager(Model, i => Url.Action("IndexPrincipal", "Reportes", new { i, search = Request.QueryString["cuenta"] }))
            </div>
        </div>
    </div>
</div>