PowerBi/Models/User/Rol.cs
using Core.Models.Common;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Core.Models.User
{
	public class Rol : Entity
	{
        [DisplayName("Perfil")]
		public string Name { get; set; }
	}
}

PowerBi/Models/User/User.cs
using Core.Models.Common;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using TarjetasColpatria.Models.Permisos;

namespace Core.Models.User
{
	public class User : Entity
	{
        [DisplayName("Documento")]
		public string Document { get; set; }
        [DisplayName("Nombres")]
        public string Names { get; set; }
        [DisplayName("Apellidos")]
        public string LastName { get; set; }
        [DisplayName("Telefono 1")]
        public string Phone1 { get; set; }
        [DisplayName("Telefono 2")]
        public string Phone2 { get; set; }
        [DisplayName("Telefono 3")]
        public string Phone3 { get; set; }
        [DisplayName("Correo")]
        public string Email { get; set; }
        [DisplayName("Estado")]
        public bool Status { get; set; }
        [DisplayName("password")]
        public string PassWord { get; set; }

        public string login { get; set; }

        public List<UserRol> UserRol { get; set; }

  
        public Guid? CoordinadorId { get; set; }

        [ForeignKey("CoordinadorId")]
        public User Coordinador { get; set; }

      
       
    }
}

PowerBi/Models/User/UserRol.cs
using Core.Models.Common;
using Core.Models.configuration;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Core.Models.User
{
	public class UserRol : Entity
	{
        [DisplayName("Perfil")]
		public Guid RolId { get; set; }

        [DisplayName("Usuario")]
        public Guid UserId { get; set; }

		[ForeignKey("RolId")]
		public Rol Rol  { get; set; }

		[ForeignKey("UserId")]
		public User User { get; set; }
	}
}

PowerBi/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Core.Models.Security;
using Core.Models.User;
using Core.Models;
using TarjetasColpatria.ViewModel;
using PagedList;


namespace PowerBi.Controllers
{
    [CustomAuthorize(Roles = "Administrador")]
    public class UsersController : Controller
    {
        private Contexto db = new Contexto();

        /*------------------------------------------------------*
        * ADMINISTRACION DE USUARIOS
        *------------------------------------------------------*/

        // GET: Users
        public ActionResult Index(List<string> camp, string documento, string nombre, int? i)
        {           
          

            if (!string.IsNullOrEmpty(documento) || !string.IsNullOrEmpty(nombre))
            {
                var users = db.Usuario.Where(x => x.Document.Trim().Contains(documento.Trim()) || x.Names.Trim().Contains(nombre.Trim())).ToList();

                ViewBag.Campana = new SelectList(db.campanas, "Id", "Nombre");
                ViewBag.Dashboard = new SelectList(db.Dashboard, "Id", "Nombre");
                ViewBag.Reportes = new SelectList(db.Reportes, "Id", "Nombre");

                ViewBag.users = users.ToList().ToPagedList(i ?? 1, 10);

                return View();


            }
            else
            {
                var users = db.Usuario.ToList();

                ViewBag.Campana = new SelectList(db.campanas, "Id", "Nombre");
                ViewBag.Dashboard = new SelectList(db.Dashboard, "Id", "Nombre");
                ViewBag.Reportes = new SelectList(db.Reportes, "Id", "Nombre");

                ViewBag.users = users.ToList().ToPagedList(i ?? 1, 10);

                return View();


            }


        }

        public JsonResult GetDashboards(Guid Id)
        {
            var dash = db.Dashboard.Where(c => c.CampanaId == Id);
            return Json(dash);
        }

        public JsonResult GetReportes(Guid Id)
        {
            var Reports = db.Reportes.Where(c => c.DashboardId == Id);
            return Json(Reports);
        }


        public JsonResult GetPermisos(Guid? Id)
        {
            var Permisos = db.permisosdash.Include(c => c.PermisosuserId).Include(c => c.dashboardId).Include(c => c.campanaId).Include(c => c.reportesId).Where(c => c.PermisosUsers == Id);
            return Json(Permisos);
        }



        // GET: Users/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Usuario.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Document,Names,LastName,Phone1,Phone2,Phone3,Email,Status,PassWord,login,CreatedAt,UpdatedAt,DeletedAt,CreatedBy,UpdatedBy")] User user)
        {
            if (ModelState.IsValid)
            {
                user.Id = Guid.NewGuid();
                db.Usuario.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Usuario.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Document,Names,LastName,Phone1,Phone2,Phone3,Email,Status,PassWord,login,CreatedAt,UpdatedAt,DeletedAt,CreatedBy,UpdatedBy")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Usuario.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            User user = db.Usuario.Find(id);
            db.Usuario.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        /*------------------------------------------------------*
        * ADMINISTRACION DE ROLES
        *------------------------------------------------------*/
        
        public ActionResult Roles(Guid Id)
        {
            User Usuario = db.Usuario.Find(Id);
            if (Id == null || Usuario == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ViewBag.Name = Usuario.Names;      
            ViewBag.Id = Id;
            ViewBag.UsersRol = db.UsuariosRoles.Include(u => u.Rol).Include(u => u.User).Where(p => p.UserId == Id);
            ViewBag.RolId = new SelectList(db.Roles, "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Roles([Bind(Include = "Id,RolId,UserId")] UserRol userRol, string Name)
        {
            if (ModelState.IsValid)
            {
                var Exist = db.UsuariosRoles
                    .Where(
                    c => c.UserId == userRol.UserId&&
                    c.RolId == userRol.RolId
                ).FirstOrDefault();

                if (Exist != null)
                {
                    ModelState.AddModelError("RolId", "este permiso ya fue asignado");
                }
                else
                {
                    userRol.Id = Guid.NewGuid();
                    db.UsuariosRoles.Add(userRol);
                    db.SaveChanges();
                    return RedirectToAction("Roles", new { Id = userRol.UserId});
                }


            }
            var Id = userRol.UserId;
            ViewBag.Name = Name;
            ViewBag.Id = Id;
            ViewBag.UsersRol = db.UsuariosRoles.Include(u => u.Rol).Include(u => u.User).Where(p => p.UserId == Id);
            ViewBag.RolId = new SelectList(db.Roles, "Id", "Name");
            return View("Roles");
        }

        // POST: UserOfPointOfCares/Delete/5
        [HttpPost, ActionName("DeleteRol")]
        [ValidateAntiForgeryToken]
        public ActionResult RolesDeleteConfirmed(Guid id)
        {
            UserRol UsusarioRol = db.UsuariosRoles.Find(id);
            var UserId = UsusarioRol.UserId;
            db.UsuariosRoles.Remove(UsusarioRol);
            db.SaveChanges();
            return RedirectToAction("Roles", new { Id = UserId });
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PowerBi/Views/Users/Create.cshtml
@model Core.Models.User.User

@{
    ViewBag.Title = "Create";
}

@{
    ViewBag._Active = "Create";
    ViewBag._Panel = "Home";
}



<div class="box box-danger">
    <div class="box-header with-border">
        <h3 class="box-title">Crear Usuario</h3>
    </div><!-- /.box-header -->
    <div class="box-body">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="row">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-md-10">
                            <label>Documento</label>
                            @Html.EditorFor(model => model.Document, new { htmlAttributes = new { @class = "form-control" } })

                            @Html.ValidationMessageFor(model => model.Document, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-10">
                            <label>Nombre</label>
                            @Html.EditorFor(model => model.Names, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Names, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-10">
                            <label>Apellido</label>
                            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-10">
                            <label>Teléfono</label>
                            @Html.EditorFor(model => model.Phone1, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Phone1, "", new { @class = "text-danger" })
                        </div>
                    </div>

                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-md-10">
                            <label>Correo</label>
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-10">
                            <label>Estado</label>
                            <select id="Status" name="Status" class="form-control">
                                <option value="false">Seleccione</option>
                                <option value="true">Activo</option>
                                <option value="false">Inactivo</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-10">
                            <label>Contraseña</label>
                            @Html.EditorFor(model => model.PassWord, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
                            @Html.ValidationMessageFor(model => model.PassWord, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-10">
                            <label>Login</label>
                            @Html.EditorFor(model => model.login, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.login, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>


            </div><br />

            <div class="row">
                <div class="form-group">
                    <div class="col-md-10">
                        <input type="submit" value="Crear" class="btn btn-success" />
                        @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-default" })
                    </div>

                </div>
            </div><br />


        }


    </div>
</div>

PowerBi/Views/Users/Index.cshtml
@{
    //List<Core.Models.User.User> Permisos = ViewBag.users;
    IPagedList<Core.Models.User.User> Permisos = ViewBag.users;


}

@using PagedList.Mvc;
@using PagedList;

<div class="box box-danger">
    <div class="box-header with-border">
        @Html.AntiForgeryToken()
        <h3 class="box-title">Listar</h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        <div class="row">
            @using (Html.BeginForm("Index", "Users"))
            {
                <div class="col-xs-12 col-md-12 col-lg-12">
                    <div class=" col-md-3 form-group">
                        <label>Documento</label>
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-road"></i>
                            </div>
                            <input type="text" class="form-control" id="documento" name="documento" placeholder="Ingrese el documento" value="">
                        </div>
                    </div>
                    <div class=" col-md-3 form-group">
                        <label>Nombre</label>
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-road"></i>
                            </div>
                            <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Ingrese el nombre" value="">
                        </div>
                    </div>
                    <div class="col-md-6 inline-form form-group">
                        <label for=""> Acciones </label>
                        <div class="input-group">
                            <input type="submit" class="btn btn-primary" id="btnCon" value="consultar">
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
</div>




<div class="box box-danger">
    <div class="box-header with-border">
        <h3 class="box-title">Listar Usuarios</h3>
    </div><!-- /.box-header -->
    <div class="box-body">

        <div class="row">
            <div class="col-md-12">
                <br />
                <table class="table table-bordered table-hover table-striped">
                    <thead>
                        <tr>

                            <th>Documento</th>
                            <th>Nombre</th>
                            <th>Apellidos</th>
                            <th>Teléfono</th>
                            <th>Correo Electrónico</th>
                            <th>Estado</th>
                            <th>Acciones</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var i in Permisos)
                        {
                           
                              var status = i.Status == true ? "Activo" : "Inactivo";
                            
                            <tr>
                                <td>
                                    @i.Document
                                </td>

                                <td>
                                    @i.Names
                                </td>

                                <td>
                                    @i.LastName
                                </td>

                                <td>
                                    @i.Phone1
                                </td>

                                <td>
                                    @i.Email
                                </td>

                                <td>
                                    @status
                                </td>



                                <td>
                                    @Html.ActionLink("Editar", "Edit", new { id = i.Id }, new { @class = "btn  btn-success btn-flat margin" })
                                    @Html.ActionLink("Detalle", "Details", new { id = i.Id }, new { @class = "btn btn-default btn-flat margin" })
                                    @Html.ActionLink("Perfiles", "Roles", new { id = i.Id }, new { @class = "btn bg-orange btn-flat margin" })
                                    <button type="button" class="btn btn-danger btn-flat margin consultarUsuarioPermisos" data-id="@i.Id">
                                        Permisos
                                    </button>

                                </td>


                            </tr>
                        }
                    </tbody>
                </table>
                @Html.PagedListPager(Permisos, i => Url.Action("Index", "Users", new { i, search = Request.QueryString["documento"] }))
             
            </div>

        </div>


    </div>

</div>



<div class="modal fade  " id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">


    <div class="modal-dialog modal-lg" role="document">
        <div class="box box-danger">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h1></h1>
                    <div class="row">
                        <div class="col-md-12">
                            <h4><span class="label label-danger center-block"> Permisos Dash</span></h4>
                        </div>
                    </div>

                </div>


                <div class="modal-body">
                    <div class="box-body">
                        <div class="row">
                            <div class="col-md-12">

                                @using (Html.BeginForm())
                                {
                                    @Html.AntiForgeryToken()

                                    <div class="form-horizontal">
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Campana</label>
                                                <div class="form-horizontal">
                                                    @Html.DropDownList("Campana", null, "Sin Seleccionar", htmlAttributes: new { @class = "form-control  " })
                                                </div>
                                            </div>

                                            <div class=" col-md-5 ">

                                                <label>Dashboard</label>
                                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                                <div class="form-group">
                                                    <span class="input-group-btn">
                                                        @Html.DropDownList("Dashboard", null, "Sin Seleccionar", htmlAttributes: new { @class = "form-control select2" })
                                                    </span>


                                                </div>

                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-8">
                                                <label>Reportes</label>
                                                <div class="form-horizontal ">

                                                    <span class="input-group-btn">
                                                        @Html.DropDownList("Reportes", null, "Sin Seleccionar", htmlAttributes: new { @class = "form-control select2" })
                                                    </span>
                                                </div>


                                            </div>
                                            <div class="form-group">
                                                <div class="modal-footer ">

                                                    @*<button type="button" id="modal" class="btn btn-danger center-block">Guardar</button>*@

                                                    <button type="button" class="btn btn-danger btn-flat margin CrearUsuarioPermisos" data-id="Id">
                                                        Guardar
                                                    </button>


                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-12">
                                                <h4><span class="label label-danger center-block">Lista Permisos Dash</span></h4>
                                                <table class="table table-bordered table-striped table-hover" id="permisos">

                                                    <thead>
                                                        <tr>
                                                            <th>
                                                                Campaña
                                                            </th>
                                                            <th>
                                                                Dashboard
                                                            </th>
                                                            <th>
                                                                Reportes
                                                            </th>
                                                            <th>
                                                                Acciones
                                                            </th>
                                                        </tr>


                                                    </thead>
                                                    <tbody></tbody>
                                                </table>
                                            </div>
                                        </div>


                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-danger center-block" data-dismiss="modal">Cerrar</button>
                                            @*@Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-danger pull-left" })
                                                <input type="submit" value="Crear" class="btn btn-success" />*@
                                        </div>


                                    </div>

                                }



                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/Scripts/Permiso.js" asp-append-version="true"></script>
    <script src="~/Scripts/modal.js" asp-append-version="true"></script>


}

PowerBi/Views/Users/Roles.cshtml
@model Core.Models.User.UserRol



@{
    ViewBag.Title = "Index";
}

@{
    ViewBag._Active = "Roles";
    ViewBag._Panel = "User";
}


<div class="box box-danger">
    <div class="box-header with-border">
        <h3 class="box-title">Agregar un rol al usuario <strong>@ViewBag.Name</strong></h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        <div class="row">
            <div class="col-md-12">

                @using (Html.BeginForm("Roles", "Users"))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.RolId, "RolId", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("RolId", null, "Sin Seleccionar", htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.RolId, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <input type="hidden" name="UserId" value="@ViewBag.Id" />
                        <input type="hidden" name="Name" value="@ViewBag.Name" />
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Crear" class="btn btn-success" />
                            </div>
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>
</div>


<div class="box box-danger">
    <div class="box-header with-border">
        <h3 class="box-title">Lista de Roles</h3>
    </div><!-- /.box-header -->
    <div class="box-body">

        <div class="row">
            <div class="col-md-12">
                <table id="tabla" class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Rol.Name)
                            </th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (Core.Models.User.UserRol item in ViewBag.UsersRol)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Rol.Name)
                                </td>
                                <td>
                                    @using (Html.BeginForm("DeleteRol", "Users", new { Id = item.Id }))
                                    {
                                        @Html.AntiForgeryToken()
                                        <div class="form-actions no-color">
                                            <input type="submit" value="Delete" class="btn btn-danger" />
                                        </div>
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div>
    @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-danger" })
</div>