PowerBi/Models/campanas.cs
using Core.Models.Common;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TarjetasColpatria.Models
{
    public class campanas : Entity
    {
        [DisplayName("Nombre")]
        public string Nombre { get; set; }

        [DisplayName("Estado")]
        public Boolean Estado { get; set; }

        public Guid? Areas { get; set; }

        //foraneas        
        [ForeignKey ("Areas")]
        [DisplayName("Area")]
        public Areas.Areas AreasId { get; set; }
      

    }
}

PowerBi/Controllers/DashboardsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Core.Models;
using Core.Models.Security;
using TarjetasColpatria.Models;
using TarjetasColpatria.Models.Dashboard;

namespace TarjetasColpatria.Controllers
{
    
    public class DashboardsController : Controller
    {
        private Contexto db = new Contexto();


        [CustomAuthorize(Roles = "Administrador,Reporting,Gerente,Soporte")]
        public ActionResult IndexPrincipal()
        {
            var dashboard = db.Dashboard.Include(c => c.campana);
            return View(dashboard.ToList());
        }

       
        // GET: Dashboards
        public ActionResult Index(Guid? Id)
        {
           
             campanas campana = db.campanas.Find(Id);
            if (campana == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ViewBag.Nombre = campana.Nombre;
            ViewBag.Id = Id;
            ViewBag.dahsboard = db.Dashboard.Include(s => s.campana).Where(u => u.CampanaId == Id);
            return View();

        }

        // GET: Dashboards/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
           
            Dashboard dashboard = db.Dashboard.Include(x => x.campana).Where(x => x.Id == id).FirstOrDefault();
            if (dashboard == null)
            {
                return HttpNotFound();
            }
            return View(dashboard);
        }
        [CustomAuthorize(Roles = "Administrador")]

        // GET: Dashboards/Create
        public ActionResult Create()
        {
          
            ViewBag.CampanaId = new SelectList(db.campanas, "Id", "Nombre");
            return View();
        }

        // POST: Dashboards/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nombre,Estado,CampanaId,DashboardId,CreatedAt,UpdatedAt,DeletedAt,CreatedBy,UpdatedBy")] Dashboard dashboard )
        {
            if (ModelState.IsValid)
            {
                dashboard.Id = Guid.NewGuid();
                db.Dashboard.Add(dashboard);
                db.SaveChanges();
                return RedirectToAction("IndexPrincipal");
            }

            var Id = dashboard.CampanaId;
            ViewBag.Nombre = dashboard.Nombre;
            ViewBag.Id = Id;
            ViewBag.dahsboard = db.Dashboard.Include(s => s.campana).Where(u => u.CampanaId == Id);
            
            return View("IndexPrincipal");
        }

        // GET: Dashboards/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dashboard dashboard = db.Dashboard.Find(id);
            if (dashboard == null)
            {
                return HttpNotFound();
            }
            ViewBag.CampanaId = new SelectList(db.campanas, "Id", "Nombre", dashboard.CampanaId);
            return View(dashboard);
        }

        // POST: Dashboards/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nombre,Estado,CampanaId,DashboardId,CreatedAt,UpdatedAt,DeletedAt,CreatedBy,UpdatedBy")] Dashboard dashboard)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dashboard).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index/"+ dashboard.CampanaId);
            }
            ViewBag.CampanaId = new SelectList(db.campanas, "Id", "Nombre", dashboard.CampanaId);
            return View(dashboard);
        }

        // GET: Dashboards/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dashboard dashboard = db.Dashboard.Find(id);
            if (dashboard == null)
            {
                return HttpNotFound();
            }
            return View(dashboard);
        }


        // POST: Dashboards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Dashboard dashboard = db.Dashboard.Find(id);
            db.Dashboard.Remove(dashboard);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PowerBi/Controllers/campanasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Core.Models;
using Core.Models.Security;
using TarjetasColpatria.Models;

namespace TarjetasColpatria.Controllers
{
    [CustomAuthorize(Roles = "Administrador")]
    public class campanasController : Controller
    {
        private Contexto db = new Contexto();

        // GET: campanas
         public ActionResult Index()
        {
            var campanas = db.campanas.Include(c => c.AreasId);
            return View(campanas.ToList());
        }

        // GET: campanas/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            campanas campanas =db.campanas.Include(J => J.AreasId).Where(c => c.Id == id).FirstOrDefault();
            //campanas campanas = db.campanas.Find(id);

            if (campanas == null)
            {
                return HttpNotFound();
            }
            return View(campanas);
        }

        // GET: campanas/Create
        public ActionResult Create()
        {
            ViewBag.Areas = new SelectList(db.areas, "Id", "Nombre");
            ViewBag.dashboard = new SelectList(db.Dashboard, "Id", "Nombre");
            return View();
        }

        // POST: campanas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nombre,Estado,Areas,dashboard,CreatedAt,UpdatedAt,DeletedAt,CreatedBy,UpdatedBy")] campanas campanas)
        {
            if (ModelState.IsValid)
            {
                campanas.Id = Guid.NewGuid();
                db.campanas.Add(campanas);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Areas = new SelectList(db.areas, "Id", "Nombre", campanas.Areas);
            return View(campanas);
        }

        // GET: campanas/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            campanas campanas = db.campanas.Find(id);
            if (campanas == null)
            {
                return HttpNotFound();
            }

            ViewBag.Areas = new SelectList(db.areas, "Id", "Nombre", campanas.Areas);
            return View(campanas);
        }

        // POST: campanas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nombre,Estado,Areas,CreatedAt,UpdatedAt,DeletedAt,CreatedBy,UpdatedBy")] campanas campanas)
        {
            if (ModelState.IsValid)
            {
                db.Entry(campanas).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Areas = new SelectList(db.areas, "Id", "Nombre", campanas.Areas);
            return View(campanas);
        }

       
        // GET: campanas/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            campanas campanas = db.campanas.Find(id);
            if (campanas == null)
            {
                return HttpNotFound();
            }
            return View(campanas);
        }

        // POST: campanas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            campanas campanas = db.campanas.Find(id);
            db.campanas.Remove(campanas);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PowerBi/Views/campanas/Create.cshtml
@model TarjetasColpatria.Models.campanas

@{
    ViewBag.Title = "Create";
}

@{
    ViewBag._Active = "Create";
    ViewBag._Panel = "Home";
}



<div class="box box-danger">
    <div class="box-header with-border">
        <h3 class="box-title">Crear Cuentas o Campañas</h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        <div class="row">
            <div class="col-md-12">

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })

                                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                            </div>
                        </div>
                                               
                        <div class="form-group">
                            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <select id="Estado" name="Estado" class="form-control">
                                    <option value="false">Seleccione</option>
                                    <option value="true">Activo</option>
                                    <option value="false">Inactivo</option>
                                </select>
                            </div>
                        </div>


                        <div class="form-group">
                            @Html.LabelFor(model => model.Areas, "Areas", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("Areas", null, "Sin Seleccionar", htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Areas, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Crear" class="btn btn-success" />
                                @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-default" })

                            </div>
                        </div>
                    </div>
                }

             
            </div>
        </div>
    </div>
</div>

PowerBi/Views/campanas/Delete.cshtml
@model TarjetasColpatria.Models.campanas

@{
    ViewBag.Title = "Delete";
}

@{
    ViewBag._Active = "Delete";
    ViewBag._Panel = "Home";
}


<div class="box box-danger">
    <div class="box-header with-border">
        <h3 class="box-title">¿Esta seguro que desea eliminar este elemento?</h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        <div class="row">
            <div class="col-md-12 col-xs-12 col-sm-12">
                <table id="tabla" class="table table-bordered table-hover">
                    <tbody>

                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Nombre)
                            </th>

                            <td>
                                @Html.DisplayFor(model => model.Nombre)
                            </td>
                        </tr>

                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Estado)
                            </th>

                            <td>
                                @Html.DisplayFor(model => model.Estado)
                            </td>
                        </tr>



                        <tr>
                            <th>
                                Fecha de Creación
                            </th>

                            <td>
                                @Html.DisplayFor(model => model.CreatedAt)
                            </td>
                        </tr>


                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Eliminar" class="btn btn-danger" />
        @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-default" })
    </div>
}

PowerBi/Views/campanas/Details.cshtml
@model TarjetasColpatria.Models.campanas



<div class="box box-danger">
    <div class="box-header with-border">
        <h3 class="box-title">Detalle Cuentas o Campañas</h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        <div class="row">
            <div class="col-md-12 col-xs-12 col-ms-12">
                <table id="tabla" class="table table-bordered table-hover">
                    <tbody>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.AreasId)
                            </th>

                            <td>
                                @Html.DisplayFor(model => model.AreasId.Nombre)
                            </td>
                        </tr>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Nombre)
                            </th>

                            <td>
                                @Html.DisplayFor(model => model.Nombre)
                            </td>
                        </tr>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Estado)
                            </th>

                            <td>
                                @Html.DisplayFor(model => model.Estado)
                            </td>
                        </tr>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.CreatedAt)
                            </th>

                            <td>
                                @Html.DisplayFor(model => model.CreatedAt)
                            </td>
                        </tr>
                       
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }, new { @class = "btn btn-success" })
    @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-default" })
</p>

PowerBi/Views/campanas/Edit.cshtml
@model TarjetasColpatria.Models.campanas




<div class="box box-success">
    <div class="box-header with-border">
        <h3 class="box-title">Editar Cuentas o Campañas</h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        <div class="row">
            <div class="col-md-12">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Id)

                        <div class="form-group">
                            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                            </div>
                        </div>

                      

                        @if (Model.Estado)
                        {
                            <div class="form-group">
                                @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    <select id="Estado" name="Estado" class="form-control">
                                        <option value=""></option>
                                        <option value="true" selected>Activo</option>
                                        <option value="false">Inactivo</option>
                                    </select>
                                </div>
                            </div>
                        }
                        else
                        {
                            <div class="form-group">
                                @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    <select id="Estado" name="Estado" class="form-control">
                                        <option value=""></option>
                                        <option value="true">Activo</option>
                                        <option value="false" selected>Inactivo</option>
                                    </select>
                                </div>
                            </div>
                        }

                        <div class="form-group">
                            @Html.LabelFor(model => model.Areas, "Areas", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("Areas", null, "Sin Seleccionar", htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Areas, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Guardar" class="btn btn-success" />
                                @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-default" })

                            </div>
                        </div>
                    </div>
                }

               
            </div>
        </div>
    </div>
</div>




@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PowerBi/Views/campanas/Index.cshtml
@model IEnumerable<TarjetasColpatria.Models.campanas>

@{
    ViewBag.Title = "Index";
}

@{
    ViewBag._Active = "Index";
    ViewBag._Panel = "Home";
}



@*<div class="box box-danger">
        <div class="box-header with-border">
            <h3 class="box-title">Listar</h3>
        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-xs-12 col-md-12 col-lg-12">
                    <div class=" col-md-3 form-group">
                        <label>Nombre</label>
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-road"></i>
                            </div>
                            <input type="text" class="form-control" id="txt_nombre" value="">
                        </div>
                    </div>
                    <div class="col-md-6 inline-form form-group">
                        <label for=""> Acciones </label>
                        <div class="input-group">
                            <input type="submit" class="btn btn-primary" id="btnCon" value="consultar">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>*@



<div class="box box-danger">
    <div class="box-header with-border">
        <h3 class="box-title">Lista Cuentas o Campañas</h3>
    </div><!-- /.box-header -->
    <div class="box-body">

        <div class="row">
            <div class="col-md-12">
                <table id="tabla" class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>
                                Areas
                            </th>
                            <th>
                                Cuenta
                            </th>
                            <th>
                                Estado
                            </th>

                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {
                            var estado = item.Estado == true ? "Activo" : "Inactivo";
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.AreasId.Nombre)
                                </td>

                                <td>
                                    @Html.DisplayFor(modelItem => item.Nombre)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => estado)
                                </td>

                                <td>
                                    @Html.ActionLink("Editar", "Edit", new { id = item.Id }, new { @class = "btn btn-xs btn-success" })
                                    @Html.ActionLink("Detalle", "Details", new { id = item.Id }, new { @class = "btn btn-xs btn-default" })
                                    @Html.ActionLink("Eliminar", "Delete", new { id = item.Id }, new { @class = "btn btn-xs btn-danger" })
                                    @Html.ActionLink("Dashboard", "Index", "Dashboards", new { id = item.Id }, new { @class = "btn btn-xs bg-orange" })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>