PowerBi/Models/Security/Accounts.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Core.Models.Security
{
	public class Accounts
	{
		public Guid? Id { get; set; }
		public string UserName { get; set; }
		public string Password { get; set; }
		public string[] Roles { get; set; }
        public List<ReportsPermisos> Permisos { get; set; }
	}

    public class ReportsPermisos
    {
        public Guid Id { get; set; }
        public string Campana { get; set; }
        public string DashBoard { get; set; }
        public string Nombre { get; set; }

        

    }
}

PowerBi/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Core.Models.Security;
using Core.Models;
using TarjetasColpatria.Models.Reportes;
using System.Threading.Tasks;
using PowerBIEmbedded_AppOwnsData.Models;
using Microsoft.IdentityModel.Clients.ActiveDirectory;
using Microsoft.Rest;
using Microsoft.PowerBI.Api.V2;
using Microsoft.PowerBI.Api.V2.Models;
using Grpc.Core;
using System.IO;

namespace PowerBi.Controllers
{
    public class AccountsController : Controller
    {

        private static readonly string Username = ConfigurationManager.AppSettings["pbiUsername"];
        private static readonly string Password = ConfigurationManager.AppSettings["pbiPassword"];
        private static readonly string AuthorityUrl = "https://login.windows.net/common/oauth2/authorize/";//ConfigurationManager.AppSettings["authorityUrl"];
        private static readonly string ResourceUrl = "https://analysis.windows.net/powerbi/api";// ConfigurationManager.AppSettings["resourceUrl"];
        private static readonly string ClientId = ConfigurationManager.AppSettings["clientId"];
        private static readonly string ApiUrl = "https://api.powerbi.com/";// ConfigurationManager.AppSettings["apiUrl"];
        private static string GroupId = ConfigurationManager.AppSettings["groupId"];
        private static string ReportId = ConfigurationManager.AppSettings["reportId"];


        private Contexto db = new Contexto();

        // GET: Accounts
        public ActionResult Index()
        {
            if (SessionPersister.Id != null)
                return RedirectToAction("Home");

            return View();
        }

        // GET: Accounts

        [CustomAuthorize]
        public ActionResult Home(Guid? Id = null)
        {
            if (Id != null)
            {

                Reportes Reporte = db.Reportes.Find(Id);
                ViewBag.Reporte = Reporte;


                if (Reporte != null)
                    if (Reporte.TIPO_REPORTE.ToString().Equals("9009b408-96e8-421a-85ac-03b6d75f9cdf"))//Reporte
                    {
                        return RedirectToAction("EmbedReport/" + Id);
                    }
                    else
                    {
                        return RedirectToAction("EmbedDashboard/" + Id);
                    }

            }

            return View();

        }

        
        [CustomAuthorize]
        public async Task<ActionResult> EmbedReport(string username, string roles, Guid id)
        {
            #region CODIGO_ANTERIOR
            //Reportes reportes = db.Reportes.Find(id);

            //if (reportes == null)
            //{
            //    return HttpNotFound();
            //}


            ////Con la identificacion del reporte verifico a que campaña a la que pertenece y busco dentro de la tabla PermisosDashes si en verda tieneel permiso asociado

            //ViewBag.NombreReporte = reportes.Nombre.ToUpper();
            //string nombreLogo= db.Logos.Where(x => x.Estado && x.ReporteId == reportes.Id).Select(x => x.Ruta).FirstOrDefault();
            //string ruta = "/Resources/Logos/" + nombreLogo;
            //ViewBag.RutaReporte = ruta;



            //GroupId = reportes.WORKGROUP_ID;
            //ReportId = reportes.REPORT_ID;
            //ViewBag.NombreReporte = reportes.Nombre;

            //var result = new EmbedConfig();
            //try
            //{
            //    result = new EmbedConfig { Username = username, Roles = roles };
            //    var error = GetWebConfigErrors();
            //    if (error != null)
            //    {
            //        result.ErrorMessage = error;
            //        return View(result);
            //    }

            //    // Create a user password cradentials.
            //    var credential = new UserPasswordCredential(Username, Password);

            //    // Authenticate using created credentials
            //    var authenticationContext = new AuthenticationContext(AuthorityUrl);

            //    var authenticationResult = await authenticationContext.AcquireTokenAsync(ResourceUrl, ClientId, credential);

            //    if (authenticationResult == null)
            //    {
            //        result.ErrorMessage = "Authentication Failed.";
            //        return View(result);
            //    }

            //    var tokenCredentials = new TokenCredentials(authenticationResult.AccessToken, "Bearer");

            //    // Create a Power BI Client object. It will be used to call Power BI APIs.
            //    using (var client = new PowerBIClient(new Uri(ApiUrl), tokenCredentials))
            //    {
            //        // Get a list of reports.
            //        var reports = await client.Reports.GetReportsInGroupAsync(GroupId);

            //        Report report;
            //        if (string.IsNullOrEmpty(ReportId))
            //        {
            //            // Get the first report in the group.
            //            report = reports.Value.FirstOrDefault();
            //        }
            //        else
            //        {
            //            report = reports.Value.FirstOrDefault(r => r.Id == ReportId);
            //        }

            //        if (report == null)
            //        {
            //            result.ErrorMessage = "Group has no reports.";
            //            return View(result);
            //        }

            //        var datasets = await client.Datasets.GetDatasetByIdInGroupAsync(GroupId, report.DatasetId);
            //        result.IsEffectiveIdentityRequired = datasets.IsEffectiveIdentityRequired;
            //        result.IsEffectiveIdentityRolesRequired = datasets.IsEffectiveIdentityRolesRequired;
            //        GenerateTokenRequest generateTokenRequestParameters;
            //        // This is how you create embed token with effective identities
            //        if (!string.IsNullOrEmpty(username))
            //        {
            //            var rls = new EffectiveIdentity(username, new List<string> { report.DatasetId });
            //            if (!string.IsNullOrWhiteSpace(roles))
            //            {
            //                var rolesList = new List<string>();
            //                rolesList.AddRange(roles.Split(','));
            //                rls.Roles = rolesList;
            //            }
            //            // Generate Embed Token with effective identities.
            //            generateTokenRequestParameters = new GenerateTokenRequest(accessLevel: "view", identities: new List<EffectiveIdentity> { rls });
            //        }
            //        else
            //        {
            //            // Generate Embed Token for reports without effective identities.
            //            generateTokenRequestParameters = new GenerateTokenRequest(accessLevel: "view");
            //        }

            //        var tokenResponse = await client.Reports.GenerateTokenInGroupAsync(GroupId, report.Id, generateTokenRequestParameters);

            //        if (tokenResponse == null)
            //        {
            //            result.ErrorMessage = "Failed to generate embed token.";
            //            return View(result);
            //        }

            //        // Generate Embed Configuration.
            //        result.EmbedToken = tokenResponse;
            //        result.EmbedUrl = report.EmbedUrl;
            //        result.Id = report.Id;


            //        //prueba
            //        var ejemplo = report.Id;
            //        ViewBag.ReporteId = report.Id;

            //        return View(result);
            //    }
            //}
            //catch (HttpOperationException exc)
            //{
            //    result.ErrorMessage = string.Format("Status: {0} ({1})\r\nResponse: {2}\r\nRequestId: {3}", exc.Response.StatusCode, (int)exc.Response.StatusCode, exc.Response.Content, exc.Response.Headers["RequestId"].FirstOrDefault());
            //}
            //catch (Exception exc)
            //{
            //    result.ErrorMessage = exc.ToString();
            //}

            #endregion

            ViewBag.reporteId = id;
            ViewBag.url = ConfigurationManager.AppSettings["Url"];

            return View();
        }

        public async Task<ActionResult> EmbedDashboard(Guid id)
        {

            Reportes reportes = db.Reportes.Find(id);

            GroupId = reportes.WORKGROUP_ID;
            ReportId = reportes.REPORT_ID;
            ViewBag.NombreReporte = reportes.Nombre;


            var error = GetWebConfigErrors();
            if (error != null)
            {
                return View(new EmbedConfig()
                {
                    ErrorMessage = error
                });
            }

            // Create a user password cradentials.
            var credential = new UserPasswordCredential(Username, Password);

            // Authenticate using created credentials
            var authenticationContext = new AuthenticationContext(AuthorityUrl);
            var authenticationResult = await authenticationContext.AcquireTokenAsync(ResourceUrl, ClientId, credential);

            if (authenticationResult == null)
            {
                return View(new EmbedConfig()
                {
                    ErrorMessage = "Authentication Failed."
                });
            }

            var tokenCredentials = new TokenCredentials(authenticationResult.AccessToken, "Bearer");

            // Create a Power BI Client object. It will be used to call Power BI APIs.
            using (var client = new PowerBIClient(new Uri(ApiUrl), tokenCredentials))
            {
                // Get a list of dashboards.
                var dashboards = await client.Dashboards.GetDashboardsInGroupAsync(GroupId);

PowerBi/Views/Accounts/AccessDenied.cshtml
@{
    ViewBag.Title = "Index";
}



<div class="container py-5">
    <div class="row">
        <div class="col-md-2 text-center">
            <p><i class="fa fa-exclamation fa-5x"></i><br />Status Code: 403</p>
        </div>
        <div class="col-md-10">
            <h3>OPPSSS!!!! Lo siento...</h3>
            <p>Lo siento,No tienes acceso a esta pagina  por razones de seguridad y de datos sensibles.<br />por favor regresa a la pagina anterior para que sigas Revisando.</p>
            <a class="btn btn-danger" href="javascript:history.back()">Regresar</a>
        </div>
    </div>
</div>

<div id="footer" class="text-center">
    &copy;Uno27 2018, Todos los derechos reservados.
</div>

PowerBi/Views/Accounts/EmbedDashboard.cshtml
@{
    ViewBag.Title = "EmbedDashboard";
    Layout = "~/Views/Shared/_LayoutAsesor.cshtml";
}


@if (!string.IsNullOrEmpty(Model.ErrorMessage))
{
    <div id="errorWrapper">
        <h2>
            Error
        </h2>
        @Model.ErrorMessage
    </div>

    return;
}

<h2>@ViewBag.NombreReporte</h2>

<div id="dashboardContainer"></div>
<div class="infoBox">
    Code is in files:<br />
    1) HomeController.cs<br />
    2) EmbedDashboard.cshtml
</div>
@Html.Partial("LiveDemoLink")

@section Scripts {


    <script>

    $(document).ready(function () {

    // Read embed application token from Model
    var accessToken = "@Model.EmbedToken.Token";

    // Read embed URL from Model
    var embedUrl = "@Html.Raw(Model.EmbedUrl)";

    // Read dashboard Id from Model
    var embedDashboardId = "@Model.Id";

    // Get models. models contains enums that can be used.
    var models = window['powerbi-client'].models;

    // Embed configuration used to describe the what and how to embed.
    // This object is used when calling powerbi.embed.
    // This also includes settings and options such as filters.
    // You can find more information at https://github.com/Microsoft/PowerBI-JavaScript/wiki/Embed-Configuration-Details.
    var config = {
        type: 'dashboard',
        tokenType: models.TokenType.Embed,
        accessToken: accessToken,
        embedUrl: embedUrl,
        id: embedDashboardId
    };

    // Get a reference to the embedded dashboard HTML element
    var dashboardContainer = $('#dashboardContainer')[0];

    // Embed the dashboard and display it within the div container.
        var dashboard = powerbi.embed(dashboardContainer, config);

    });

    </script>

    <script src="https://npmcdn.com/es6-promise@3.2.1"></script>
    <script src="~/scripts/powerbi.js"></script>

}

PowerBi/Views/Accounts/EmbedReport.cshtml
@{
    ViewBag.Title = "EmbedReport";
    Layout = "~/Views/Shared/_LayoutAsesor.cshtml";

    var reporteId = ViewBag.reporteId;
    var url = ViewBag.url;

}

    <style>
        body {
            margin: 0; /* Reset default margin */
        }

        #iframeFather {
            border: none;
            height: 100vh !important;
            width: 100vw !important;
            margin-left: -150px !important;
        }
    </style>

<div class="row">
    <div class="col">
        <iframe id="iframeFather" title="Inline Frame Example" src="@url?id=@reporteId">
        </iframe>
    </div>
</div>





@Html.Partial("LiveDemoLink")

PowerBi/Views/Accounts/Home.cshtml
@using TarjetasColpatria.Models.Reportes;
@{

    ViewBag.Title = "Home Page";
    Layout = "../Shared/_LayoutAsesor.cshtml";

    //Reportes Reporte = new Reportes() { };
    //if(ViewBag.Reporte != null)
    //{

    //Reporte = ViewBag.Reporte;
    //}


}

<div>Uno27 Esta Contigo</div>

@*<iframe src="@Reporte.url"
    frameborder="0"></iframe>*@

@*@section Scripts {
    <script>
        var width = $(window).width() - 300;
        var height = $(window).height() - 90;
        $("iframe").width(width);
        $("iframe").height(height );

        window.onresize = function () {
            var width = $(window).width() - 300;
            var height = $(window).height() - 90;
            $("iframe").width(width);
            $("iframe").height(height);
        }


    </script>

    }*@

PowerBi/Views/Accounts/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "../Shared/_LayoutPrincipal.cshtml";
    string imagePath = "/Content/images/fondo.jpg";
}
@model  Core.Models.Security.AccountsViewModel

<style>
    img.logo{
        /*box-shadow: 5px 5px 500px  #ff0000;*/
        margin-bottom: 20px;
        width: 300px;
    }
    /*.croseling{
        height: 60vh;
        width: 100vw;
    }*/

    html body {
        background ="~/Content/Images/fondo-triangulos-02.png" bgcolor="aqua">
    }

    html body .box-body {
        background-color:  transparent;
    }


        html body .box-body input[type="text"], html body .box-body input[type="password"] {
            background-color: #E1007B;
            border-radius: 10px;
            border: none !important;
            color: #fff;
            font-weight: bold;
        }

            html body .box-body input[type="text"]::placeholder { /* Firefox, Chrome, Opera */
                color: #fff;
                font-weight: bold;
            }


    .blanco {
        background-color: #fff !important;
        color: #aaa !important;
        font-weight: bold;
        
    }

        .blanco::placeholder, .blanco:-ms-input-placeholder, .blanco::-ms-input-placeholder { /* Microsoft Edge */
            color: orange;
        } { /* Firefox, Chrome, Opera */
            color: #aaa;
            font-weight: bold;
        }


    .box-body{
        position:fixed;
        bottom: 15%;
        width: 600px;
    }


    /*==================================================*/
    /* BACKGROUND
  /*==================================================*/
    .skin-black-light .wrapper, .skin-black-light .main-sidebar, .skin-black-light .left-side {
        /* background-color: #f9fafc; */
        background-color: none !important;
    }
    body {
        /* Location of the image */
        background-image: url("/Content/images/fondo.jpg");
        /* Background image is centered vertically and horizontally at all times */
        background-position: center center;
        /* Background image doesn't tile */
        background-repeat: no-repeat;
        /* Background image is fixed in the viewport so that it doesn't move when
     the content's height is greater than the image's height */
        background-attachment: fixed;
        /* This is what makes the background image rescale based
     on the container's size */
        background-size: cover;
        /* Set a background color that will be displayed
     while the background image is loading */
        background-color: #464646;
    }


    @@media only screen and (max-width: 767px) {
      body {
        /* The file size of this background image is 93% smaller
           to improve page load speed on mobile internet connections */
        /*background-image: url(images/background-photo-mobile-devices.jpg);*/
      }
    }


</style>
<header>
    @*<meta content="1" http-equiv="refresh" />*@
</header>
<div class="row">
    <div class="col-md-3">
        @*<img src="~/Content/images/uno27_claro.png"  class="logo croseling" />*@
    </div>
    <div class="col-md-offset-9">
        @*<img src="~/Content/images/logo2.png" class="logo" />*@
        <img src="~/Content/images/logo.png" class="logo" />

    </div>
    <div class="col-md-3">
        @*<img src="~/Content/images/uno27_claro.png"  class="logo croseling" />*@
    </div>
    <div class="col-md-offset-1 col-md-5">
    
            <div class="box-body">
                @using (Html.BeginForm("Login", "Accounts", FormMethod.Post))
                {

                    <div class="form-group">
                        <br />
                        
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Accounts.UserName, new { htmlAttributes = new { @class = "form-control", autofocus = "",placeholder="Usuario" } })
                        </div>
                    </div>

                    <div class="form-group">
                        <br />
                        <br />

                        
                        <div class="col-md-10">
                            @Html.PasswordFor(model => model.Accounts.Password, new { @class = "form-control blanco", placeholder = "Contraseña" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-2"></label>
                        <div class="col-md-10">
                            <br />
                            <input type="submit" name="send" value="Ingresar" class="btn bg-black" />
                            @if (ViewBag.Error != null)
                            {
                                <div class="alert alert-danger">@ViewBag.Error</div>
                            }
                        </div>
                    </div>


                }
        </div>

    </div>
</div>

PowerBi/Views/Accounts/LiveDemoLink.cshtml
<!--<div class="infoBox">
    For Live demo and more code samples please visit <a href="https://microsoft.github.io/PowerBI-JavaScript/demo/v2-demo/index.html">https://microsoft.github.io/PowerBI-JavaScript/demo/v2-demo/index.html</a>
    <br />
    For JavaScript API, please visit <a href="https://github.com/Microsoft/PowerBI-javascript/wiki">https://github.com/Microsoft/PowerBI-javascript/wiki</a>
    <br />
    For RLS info, visit <a href="https://powerbi.microsoft.com/en-us/documentation/powerbi-developer-embedded-rls/">https://powerbi.microsoft.com/en-us/documentation/powerbi-developer-embedded-rls/</a>
</div>-->

PowerBi/Views/Accounts/View.cshtml
<div style="padding-top:200px;">
    <img src="~/Content/images/LOGO UNO27-02-07 (003).png" width="500px" height="400px" style="margin:0px auto ;display: block " alt="imgf" />
</div>